### ISSUE TITLE
Bulma Calendar widget shows incorrect value

### ISSUE THREAD

**Issue by bpepple** [lemonsaurus/django-simple-bulma#88]
Using the Bulma Calendar widget and notice that it's showing the incorrect date on a form.

Below screenshot shows the values it should be:
![Screenshot from 2022-03-05 15-39-13](https://user-images.githubusercontent.com/8381/156899371-67f13d7e-daf7-48c0-bdcc-4cf95cbad9e6.png)

When updating the object the Bulma-Calendar widget shows the following:
![Screenshot from 2022-03-05 15-39-25](https://user-images.githubusercontent.com/8381/156899405-f3696ae6-00f1-48a8-aa50-8088648773e1.png)

It appears to be showing a day earlier than the value of the input:
![Screenshot from 2022-03-05 15-44-46](https://user-images.githubusercontent.com/8381/156899465-ddcee6f9-9e2a-4181-bf4f-c09b1f90fa4c.png)

Did a quick look at upstreams bugs and didn't see any for this bug, but when I get some free time I'll give a more thorough search.

**Comment by bpepple** [comment]
Should have noted this is with v2.4.0, and it looks like this bug was fixed with a more recent version of Bulma-Calendar (tho I haven't had a chance to verify this).

**Comment by lemonsaurus** [comment]
I'll make sure to update Bulma-Calendar in the next release of `django-simple-bulma`, which will happen soon.

**Comment by lemonsaurus** [comment]
Has since been upgraded significantly, no reports of problem persisting in v6.x..
